name       : leocad
version    : '18.02'
release    : 5
source     :
    - https://github.com/leozide/leocad/archive/v18.02.tar.gz : 496567a9f05930b3366b38053b6de4f2c9d917280079eeb45d08581784903ca1
license    : GPL-2.0
component  : multimedia.graphics
summary    : CAD application for creating virtual LEGO models
description: |
    LeoCAD is a CAD program for creating virtual LEGO models.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake DISABLE_UPDATE_CHECK=1
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
