name       : leocad
version    : '21.06'
release    : 7
source     :
    - https://github.com/leozide/leocad/archive/refs/tags/v21.06.tar.gz : bd28c47f920fa1bc458b6e5f476b93ccc1aa40e30158a3dd2397368cc3d79099
    - https://github.com/leozide/leocad/releases/download/v21.06/Library-20.03.zip : 88d6d28b3a494a15ae63e984c1e732e28362fabc2e145ffab828fed2eb5e3632
homepage   : https://www.leocad.org/
license    :
    - CC-BY-2.0        # LDraw Library
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : CAD application for creating virtual LEGO models
description: |
    LeoCAD is a CAD program for creating virtual LEGO models. It has an intuitive interface, designed to allow new users to start creating new models without having to spend too much time learning the application.
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    unzip $sources/Library-20.03.zip
    %qmake DISABLE_UPDATE_CHECK=1 LDRAW_LIBRARY_PATH=/usr/share/leocad
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir

    # Install LDraw library
    install -Dm00644 library.bin -t $installdir/usr/share/leocad
    # Remove unnecessary files
    rm -rf $installdir/usr/share/doc
