name       : leocad
version    : 19.07.1
release    : 6
source     :
    - https://github.com/leozide/leocad/archive/v19.07.1.tar.gz : b74557e00366f1d3ddc211f9e55c28dba39987d66e5e3106490ab5fb75d25bc0
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : CAD application for creating virtual LEGO models
description: |
    LeoCAD is a CAD program for creating virtual LEGO models.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(harfbuzz)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake DISABLE_UPDATE_CHECK=1
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
