name       : leocad
version    : '23.03'
release    : 8
source     :
    - https://github.com/leozide/leocad/archive/refs/tags/v23.03.tar.gz : 69a45c60898ed07d8cf7e714442b201b0da3adc073287170eb6f46901e4604ce
    - https://github.com/leozide/leocad/releases/download/v23.03/Library-23.01.zip : 4f864ba05417ee0889b47706ea0b6a99dc8bfc3a52c9899a5b3b141cdfba970b
homepage   : https://www.leocad.org/
license    :
    - CC-BY-2.0        # LDraw Library
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : CAD application for creating virtual LEGO models
description: |
    LeoCAD is a CAD program for creating virtual LEGO models. It has an intuitive interface, designed to allow new users to start creating new models without having to spend too much time learning the application.
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    unzip $sources/Library-23.01.zip # Check Me
    %qmake DISABLE_UPDATE_CHECK=1 LDRAW_LIBRARY_PATH=/usr/share/leocad
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir

    # Install LDraw library
    install -Dm00644 library.bin -t $installdir/usr/share/leocad
    # Remove unnecessary files
    rm -rf $installdir/usr/share/doc
