name       : leocad
version    : 0.83.2
release    : 1
source     :
    - https://github.com/leozide/leocad/archive/v0.83.2.tar.gz : 4f532a2fca620e512b38c0526370900969e5f25d84cff300927887d147a94984
license    : GPL-2.0
component  : multimedia.graphics
summary    : CAD application for creating virtual LEGO models
description: |
    CAD application for creating virtual LEGO models
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(QtCore)
setup      : |
    qmake-qt4 QMAKE_CFLAGS_ISYSTEM=-I \
              QMAKE_MOC=/usr/bin/moc-qt4 \
              QMAKE_RCC=/usr/bin/rcc-qt4 \
              QMAKE_UIC=/usr/bin/uic-qt4 \
              QMAKE_CXXFLAGS="$CXXFLAGS" \
              PREFIX=/usr
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
